# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    identifier: KcgOS_ft
    url: /
    weight: 10
  - name: Topics
    identifier: O_1IP5fN
    url: tags/
    weight: 20
  - name: Posts
    identifier: f7E5bb0N
    url: /posts/
    weight: 30
