hugoblox:
  schema: "2.0"
  identity:
    name: InfraPlaybook
    type: person
    tagline: "Infrastructure simplified with tutorials "
    social:
      twitter: test
    organization: Nutanix
    description: imjustpasionatinthisfield
  theme:
    mode: system
    pack: minimal
    colors:
      primary: "#010112"
      secondary: "#ffffff"
      neutral: ""
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar-simple
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
