hugoblox:
  schema: "2.0"
  identity:
    name: InfraPlaybook
    type: person
    tagline: "Infrastructure simplified with tutorials "
    social:
      twitter: test
    organization: Nutanix
    description: imjustpasionatinthisfield
  theme:
    mode: system
    pack: minimal
    colors:
      primary: "#000000"
      secondary: "#ffffff"
      neutral: ""
    colors_light:
      primary: "#ffffff"
      secondary: "#000000"
      neutral: "#000000"
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: false
    align: center
    search: true
    theme_toggle: true
    theme_picker: false
    language_switcher: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
